### PR TITLE
[droidmedia] Change function prototypes according to AOSP Android 10.

### PR DESCRIPTION
**Pull request by AndreySV**
That fixes following build errors:

    In file included from external/droidmedia/minisf.cpp:27:
    In file included from external/droidmedia/services/services.h:65:
    external/droidmedia/services/services_10_0_0.h:50:26: error: unknown type name 'ConfigChanged'
                VsyncSource, ConfigChanged) {
                             ^
    external/droidmedia/services/services_10_0_0.h:460:10: error: 'FakeResourceManagerService::addResource' hides overloaded virtual function []
        void addResource(int, int, int64_t, const sp<IResourceManagerClient>,
             ^
    frameworks/av/media/libmedia/include/media/IResourceManagerService.h:40:18: note: hidden overloaded virtual function 'android::IResourceMan)
        virtual void addResource(
                     ^
    In file included from external/droidmedia/minisf.cpp:27:
    In file included from external/droidmedia/services/services.h:65:
    external/droidmedia/services/services_10_0_0.h:464:10: error: 'FakeResourceManagerService::removeResource' hides overloaded virtual functio]
        void removeResource(int, int64_t,
             ^
    frameworks/av/media/libmedia/include/media/IResourceManagerService.h:46:18: note: hidden overloaded virtual function 'android::IResourceMan)
        virtual void removeResource(int pid, int64_t clientId) = 0;

### CODE REVIEW

**Comment by AndreySV** [comment]
Links to AOSP code for corresponding functions:

addResource, removeResources:

https://android.googlesource.com/platform/frameworks/av/+/refs/heads/android10-release/media/libmedia/include/media/IResourceManagerService.h#40
https://android.googlesource.com/platform/frameworks/av/+/refs/heads/android10-mainline-release/media/libmedia/include/media/IResourceManagerService.h#40
https://android.googlesource.com/platform/frameworks/av/+/refs/tags/android-security-10.0.0_r52/media/libmedia/IResourceManagerService.cpp#73


createDisplayEventConnection
https://android.googlesource.com/platform/frameworks/native/+/refs/heads/android10-release/libs/gui/include/gui/ISurfaceComposer.h#99

**Comment by mlehtima** [comment]
Instead of replacing the functions please add the new definitions next to the existing versions so lineageos builds won't fail.

**Comment by AndreySV** [comment]
Thanks for the tip, but the doesn't compiled then because of unknown type ConfigChanged. 

`In file included from external/droidmedia/minimedia.cpp:41:
In file included from external/droidmedia/services/services.h:65:
external/droidmedia/services/services_10_0_0.h:50:26: error: unknown type name 'ConfigChanged'
            VsyncSource, ConfigChanged) {
`

https://android.googlesource.com/platform/frameworks/native/+/refs/heads/android10-release/libs/gui/include/gui/ISurfaceComposer.h

This type is included in following AOSP branches
`$ git branch -r --contains 0f4a1b19009a1e71ed2100b63b04aa015a111b44

  origin/HEAD -> origin/master
  origin/android10-c2f2-release
  origin/android10-c2f2-s1-release
  origin/android10-c2f2-s2-release
  origin/android10-d4-release
  origin/android10-d4-s1-release
  origin/android10-gsi
  origin/android10-mainline-media-release
  origin/android10-mainline-networking-release
  origin/android10-mainline-resolv-release
  origin/android10-mainline-tzdata-release
  origin/android10-qpr1-b-release
  origin/android10-qpr1-b-s1-release
  origin/android10-qpr1-c-release
  origin/android10-qpr1-c-s1-release
  origin/android10-qpr1-d-release
  origin/android10-qpr1-mainline-release
  origin/android10-qpr1-release
  origin/android10-qpr2-release
  origin/android10-qpr2-s1-release
  origin/android10-qpr2-s2-release
  origin/android10-qpr2-s3-release
  origin/android10-qpr2-s4-release
  origin/android10-qpr3-release
  origin/android10-qpr3-s1-release
  origin/android10-sidebranch
  origin/android11-d1-b-release
  origin/android11-d1-release
  origin/android11-d1-s1-release
  origin/android11-d1-s5-release
  origin/android11-d1-s6-release
  origin/android11-d1-s7-release
  origin/android11-dev
  origin/android11-gsi
  origin/android11-mainline-release
  origin/android11-mainline-sparse-2020-dec-release
  origin/android11-platform-release
  origin/android11-qpr1-c-release
  origin/android11-qpr1-d-release
  origin/android11-qpr1-d-s1-release
  origin/android11-qpr1-release
  origin/android11-qpr1-s1-release
  origin/android11-qpr1-s2-release
  origin/android11-qpr2-release
  origin/android11-release
  origin/android11-s1-release
  origin/android11-security-release
  origin/android11-tests-dev
  origin/android11-tests-release
  origin/master
  origin/sdk-release
  origin/simpleperf-release
  origin/tmp_b_147314974
`
And ConfigChanged is NOT included in following AOSP branches.

`
$ git branch -r --no-contains 0f4a1b19009a1e71ed2100b63b04aa015a111b44 | grep android10

origin/android10-dev
origin/android10-mainline-a-release
origin/android10-mainline-release
origin/android10-release
origin/android10-s1-release
origin/android10-s2-release
origin/android10-s3-release
origin/android10-security-release
origin/android10-tests-dev
origin/android10-tests-release
`

**Comment by AndreySV** [comment]
`
$ for i in $(git tag | grep '10.0.0'); do git checkout $i &> /dev/null; grep 'ConfigChanged' ISurfaceComposer.h &> /dev/null; if [ $? -eq 0 ]; then echo $i FOUND; else echo $i MISSING; fi; done;

android-10.0.0_r1 MISSING
android-10.0.0_r10 MISSING
android-10.0.0_r11 MISSING
android-10.0.0_r12 FOUND
android-10.0.0_r13 FOUND
android-10.0.0_r14 FOUND
android-10.0.0_r15 FOUND
android-10.0.0_r16 FOUND
android-10.0.0_r17 MISSING
android-10.0.0_r18 FOUND
android-10.0.0_r19 FOUND
android-10.0.0_r2 MISSING
android-10.0.0_r20 FOUND
android-10.0.0_r21 FOUND
android-10.0.0_r22 FOUND
android-10.0.0_r23 FOUND
android-10.0.0_r24 FOUND
android-10.0.0_r25 FOUND
android-10.0.0_r26 FOUND
android-10.0.0_r27 FOUND
android-10.0.0_r28 FOUND
android-10.0.0_r29 FOUND
android-10.0.0_r3 MISSING
android-10.0.0_r30 FOUND
android-10.0.0_r31 FOUND
android-10.0.0_r32 FOUND
android-10.0.0_r33 FOUND
android-10.0.0_r34 FOUND
android-10.0.0_r35 FOUND
android-10.0.0_r36 FOUND
android-10.0.0_r37 FOUND
android-10.0.0_r38 FOUND
android-10.0.0_r39 FOUND
android-10.0.0_r4 MISSING
android-10.0.0_r40 FOUND
android-10.0.0_r41 FOUND
android-10.0.0_r42 FOUND
android-10.0.0_r43 FOUND
android-10.0.0_r44 FOUND
android-10.0.0_r45 FOUND
android-10.0.0_r46 MISSING
android-10.0.0_r47 MISSING
android-10.0.0_r5 MISSING
android-10.0.0_r6 MISSING
android-10.0.0_r7 FOUND
android-10.0.0_r8 FOUND
android-10.0.0_r9 FOUND
android-mainline-10.0.0_r1 MISSING
android-mainline-10.0.0_r10 FOUND
android-mainline-10.0.0_r11 FOUND
android-mainline-10.0.0_r2 MISSING
android-mainline-10.0.0_r3 MISSING
android-mainline-10.0.0_r4 FOUND
android-mainline-10.0.0_r5 FOUND
android-mainline-10.0.0_r6 FOUND
android-mainline-10.0.0_r7 FOUND
android-mainline-10.0.0_r8 FOUND
android-mainline-10.0.0_r9 FOUND
android-security-10.0.0_r48 MISSING
android-security-10.0.0_r49 MISSING
android-security-10.0.0_r50 MISSING
android-security-10.0.0_r51 MISSING
android-security-10.0.0_r52 MISSING
`

**Comment by AndreySV** [comment]
Now code should compile regardless of ConfigChanged definition.

**Comment by pvuorela** [comment]
@abranson @mlehtima looking good to you guys?

**Comment by AndreySV** [comment]
any feedback would be very nice.

**Comment by mlehtima** [comment]
This failed to build both for r41 in both lineageos and aosp bases.
```
external/droidmedia/services/services_10_0_0.h:222:33: error: 'MiniSurfaceFlinger::createDisplayEventConnection' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    sp<IDisplayEventConnection> createDisplayEventConnection(
                                ^
frameworks/native/libs/gui/include/gui/ISurfaceComposer.h:101:41: note: hidden overloaded virtual function 'android::ISurfaceComposer::createDisplayEventConnection' declared here: different number of parameters (2 vs 1)
```

**Comment by AndreySV** [comment]
@mlehtima, thank you for the review. You are right, there was a problem with ConfigChanged detection  code. Unfortunately It doesn't work if enum is defined inside class in namespace and I could not find a way to get it working. So I dropped last two commits and leave only new prototypes.
I've tested build with aosp android-10.0.0_r41 (with ConfigChanged) and android-10.0.0_r48 (without ConfigChanged). Compilation succeeded. 
For Android 10 revisions without ConfigChanged enumeration small patch to frameworks/native wil be needed:

```
diff --git a/libs/gui/include/gui/ISurfaceComposer.h b/libs/gui/include/gui/ISurfaceComposer.h
index e89d3a4ce..5b8e84b29 100644
--- a/libs/gui/include/gui/ISurfaceComposer.h
+++ b/libs/gui/include/gui/ISurfaceComposer.h
@@ -90,6 +90,8 @@ public:
         eVsyncSourceSurfaceFlinger = 1
     };
 
+    enum ConfigChanged { eConfigChangedSuppress = 0, eConfigChangedDispatch = 1 };
+
     /*
      * Create a connection with SurfaceFlinger.
      */


```

**Comment by AndreySV** [comment]
@abranson @mlehtima is it ok now?

**Comment by mlehtima** [comment]
At least the code seems to build successfully now for r41 in both lineageos and aosp bases.

**Comment by mlehtima** [comment]
Could you rebase the changes? The branch is quite much behind master.

**Review by mlehtima — APPROVED** [review]

**Review by mkosola — APPROVED** [review]
